#!/bin/bash
set -e
export JULIA_PKG_PRECOMPILE_AUTO=0
julia -e 'using Pkg; Pkg.activate("."); using IJulia; installkernel("Julia", "--project", "--heap-size-hint=1G")'
julia -e 'using Pkg; Pkg.instantiate()'
