#!/bin/bash
set -e

# Instala o kernel Julia e limita uso de memória durante a instalação (recomendado para evitar erros no Binder)
export JULIA_PKG_PRECOMPILE_AUTO=0
julia -e 'using Pkg; Pkg.add("IJulia"); using IJulia; installkernel("Julia", "--heap-size-hint=1G")'

# Instala as dependências do projeto listadas no Project.toml
julia -e 'using Pkg; Pkg.instantiate()'
